import enum


class Plays(enum.Enum):
    MAKES_THREE_POINT_JUMPER = 0
    MISSES_THREE_POINT_JUMPER = 1
    MAKES_TWO_POINT = 2
    MISSES_TWO_POINT = 3
    MAKES_PULLUP = 4
    MISSES_PULLUP = 5
    BLOCK = 6
    DEFENSIVE_REBOUND = 7
    TURNOVER = 8
    SHOOTING_FOUL = 9
    MAKES_FREE_THROW_ONE_OF_ONE = 10
    MISSES_FREE_THROW_ONE_OF_ONE = 11
    MAKES_FREE_THROW_ONE_OF_TWO = 12
    MAKES_FREE_THROW_TWO_OF_TWO = 13
    MAKES_FREE_THROW_ONE_OF_THREE = 14
    MAKES_FREE_THROW_TWO_OF_THREE = 15
    MAKES_FREE_THROW_THREE_OF_THREE = 16
    MISSES_FREE_THROW_ONE_OF_TWO = 17
    MISSES_FREE_THROW_TWO_OF_TWO = 18
    MISSES_FREE_THROW_ONE_OF_THREE = 19
    MISSES_FREE_THROW_TWO_OF_THREE = 20
    MISSES_FREE_THROW_THREE_OF_THREE = 21
    OFFENSIVE_REBOUND = 22
    MAKES_DRIVING_LAYUP = 23
    MISSES_DRIVING_LAYUP = 24
    MAKES_LAYUP = 25
    MISSES_LAYUP = 26
    BAD_PASS = 27
    MAKES_DRIVING_FLOATING_JUMPSHOT = 28
    MISSES_DRIVING_FLOATING_JUMPSHOT = 29
    MAKES_THREE_POINT_PULLUP = 30
    MISSES_THREE_POINT_PULLUP = 31
    PERSONAL_FOUL = 32
    MAKES_DRIVING_DUNK = 33
    MISSES_DRIVING_DUNK = 34
    MAKES_ALLEY_OOP_DUNK_SHOT = 35
    MISSES_ALLEY_OOP_DUNK_SHOT = 36
    MAKES_RUNNING_PULLUP_JUMPSHOT = 37
    MISSES_RUNNING_PULLUP_JUMPSHOT = 38
    MAKES_STEPBACK_JUMPSHOT = 39
    MISSES_STEPBACK_JUMPSHOT = 40
    MAKES_TIP_SHOT = 41
    MISSES_TIP_SHOT = 42
    MAKES_ALLEY_OOPS_LAYUP = 43
    MISSES_ALLEY_OOPS_LAYUP = 44
    OFFENSIVE_FOUL = 45
    LOOSE_BALL_FOUL = 46
    MAKES_DUNK = 47
    MISSES_DUNK = 48
    TRAVELING = 49
    MAKES_BANK_SHOT = 50
    MAKES_HOOK_SHOT = 51
    MISSES_HOOK_SHOT = 52
    KICKED_BALL_VIOLATION = 53
    OFFENSIVE_CHARGE = 54
    VIOLATION = 55
    MAKES_FINGER_ROLL_LAYUP = 56
    MISSES_FINGER_ROLL_LAYUP = 57
    PERSONAL_TAKE_FOUL = 58
    TRANSITION_TAKE_FOUL = 59
    DEFENSIVE_THREE_SECONDS = 60
    MAKES_TECHNICAL_FREE_THROW = 61
    MISSES_TECHNICAL_FREE_THROW = 62
    HANGING_TECHFOUL = 63
    TECHNICAL_FOUL = 64
    MISSES_BANK_SHOT = 65
    FLAGRANT_FOUL_1 = 66
    MAKES_FREE_THROW_FLAGRANT_1_OF_2 = 67
    MAKES_FREE_THROW_FLAGRANT_2_OF_2 = 68
    MISSES_FREE_THROW_FLAGRANT_1_OF_2 = 69
    MISSES_FREE_THROW_FLAGRANT_2_OF_2 = 70
    MAKES_FREE_THROW_FLAGRANT_1_OF_3 = 71
    MAKES_FREE_THROW_FLAGRANT_2_OF_3 = 72
    MAKES_FREE_THROW_FLAGRANT_3_OF_3 = 73
    MISSES_FREE_THROW_FLAGRANT_1_OF_3 = 74
    MISSES_FREE_THROW_FLAGRANT_2_OF_3 = 75
    MISSES_FREE_THROW_FLAGRANT_3_OF_3 = 76
    BOTH_TEAM_FOUL = 77
    EJECTED = 78
    MAKES_RUNNING_JUMPER = 79
    MISSES_RUNNING_JUMPER = 80
    DEFENSIVE_TEAM_REBOUND = 81
    TEAM_REBOUND = 82
    LOST_BALL = 83
    AWAY_FROM_PLAY_FOUL = 84
    UNSPECIFIED_FOUL = 85
    MAKES_FREE_THROW_FLAGRANT_1_OF_1 = 86
    UNSPECIFIED_SHOT_CLOCK_TO = 87


REBOUND = 0
ASSIST = 1
STEAL = 2
BLOCK = 3
POINT = 4
FOUL = 5
TURNOVER = 6
FOUL_AND_TURNOVER = 7
BOTH_TEAM_FOUL = 8
TEAM_FOUL = 9

HOME = 0
AWAY = 1

DIST_DEFAULT_FT = 0
DIST_WITHIN_4_FT = 1
DIST_5_TO_14 = 2
DIST_15_26 = 3
DIST_27_30 = 4
DIST_30_PLUS = 5


makes_three = {Plays.MAKES_THREE_POINT_JUMPER,
              Plays.MAKES_THREE_POINT_PULLUP}

misses_three = {Plays.MISSES_THREE_POINT_JUMPER,
                Plays.MISSES_THREE_POINT_PULLUP,
                }

makes_two = {Plays.MAKES_TWO_POINT,
             Plays.MAKES_PULLUP,
             Plays.MAKES_DRIVING_LAYUP,
             Plays.MAKES_LAYUP,
             Plays.MAKES_RUNNING_PULLUP_JUMPSHOT,
             Plays.MAKES_STEPBACK_JUMPSHOT,
             Plays.MAKES_TIP_SHOT,
             Plays.MAKES_BANK_SHOT,
             Plays.MAKES_HOOK_SHOT,
             Plays.MAKES_FINGER_ROLL_LAYUP,
             Plays.MAKES_RUNNING_JUMPER}

misses_two = {Plays.MISSES_TWO_POINT,
              Plays.MISSES_PULLUP,
              Plays.MISSES_DRIVING_LAYUP,
              Plays.MISSES_LAYUP,
              Plays.MISSES_DRIVING_FLOATING_JUMPSHOT,
              Plays.MISSES_DRIVING_DUNK,
              Plays.MISSES_ALLEY_OOP_DUNK_SHOT,
              Plays.MISSES_RUNNING_PULLUP_JUMPSHOT,
              Plays.MISSES_STEPBACK_JUMPSHOT,
              Plays.MISSES_TIP_SHOT,
              Plays.MISSES_ALLEY_OOPS_LAYUP,
              Plays.MISSES_DUNK,
              Plays.MISSES_HOOK_SHOT,
              Plays.MISSES_FINGER_ROLL_LAYUP,
              Plays.MISSES_BANK_SHOT,
              Plays.MISSES_RUNNING_JUMPER}

makes_acrobatic_layups_and_dunks = {Plays.MAKES_DRIVING_FLOATING_JUMPSHOT,
                                    Plays.MAKES_DRIVING_DUNK,
                                    Plays.MAKES_ALLEY_OOP_DUNK_SHOT,
                                    Plays.MAKES_ALLEY_OOPS_LAYUP,
                                    Plays.MAKES_DUNK}

block = {Plays.BLOCK,
         }

rebound = {Plays.DEFENSIVE_REBOUND,
           Plays.OFFENSIVE_REBOUND,
           Plays.DEFENSIVE_TEAM_REBOUND,
           Plays.TEAM_REBOUND}

turnover = {Plays.TURNOVER,
            Plays.BAD_PASS,
            Plays.TRAVELING,
            Plays.KICKED_BALL_VIOLATION,
            Plays.OFFENSIVE_CHARGE,
            Plays.VIOLATION,
            Plays.DEFENSIVE_THREE_SECONDS,
            Plays.LOST_BALL,
            Plays.UNSPECIFIED_SHOT_CLOCK_TO}

foul = {Plays.SHOOTING_FOUL,
        Plays.PERSONAL_FOUL,
        Plays.OFFENSIVE_FOUL,
        Plays.LOOSE_BALL_FOUL,
        Plays.PERSONAL_TAKE_FOUL,
        Plays.TRANSITION_TAKE_FOUL,
        Plays.HANGING_TECHFOUL,
        Plays.TECHNICAL_FOUL,
        Plays.AWAY_FROM_PLAY_FOUL,
        Plays.UNSPECIFIED_FOUL,
        }

flagrant = {Plays.FLAGRANT_FOUL_1,
}

dramatic_fouls = {Plays.BOTH_TEAM_FOUL,
                  Plays.EJECTED,}

one_ft = {Plays.MAKES_FREE_THROW_ONE_OF_ONE,
          Plays.MISSES_FREE_THROW_ONE_OF_ONE,
          Plays.MAKES_FREE_THROW_FLAGRANT_1_OF_1,}

two_ft = {Plays.MAKES_FREE_THROW_ONE_OF_TWO,
          Plays.MAKES_FREE_THROW_TWO_OF_TWO,
          Plays.MISSES_FREE_THROW_ONE_OF_TWO,
          Plays.MISSES_FREE_THROW_TWO_OF_TWO,
          Plays.MAKES_FREE_THROW_FLAGRANT_1_OF_2,
          Plays.MAKES_FREE_THROW_FLAGRANT_2_OF_2,
          Plays.MISSES_FREE_THROW_FLAGRANT_1_OF_2,
          Plays.MISSES_FREE_THROW_FLAGRANT_2_OF_2,
          }

three_ft = {Plays.MAKES_FREE_THROW_ONE_OF_THREE,
            Plays.MAKES_FREE_THROW_TWO_OF_THREE,
            Plays.MAKES_FREE_THROW_THREE_OF_THREE,
            Plays.MISSES_FREE_THROW_ONE_OF_THREE,
            Plays.MISSES_FREE_THROW_TWO_OF_THREE,
            Plays.MISSES_FREE_THROW_THREE_OF_THREE,
            Plays.MAKES_FREE_THROW_FLAGRANT_1_OF_3,
            Plays.MAKES_FREE_THROW_FLAGRANT_2_OF_3,
            Plays.MAKES_FREE_THROW_FLAGRANT_3_OF_3,
            Plays.MISSES_FREE_THROW_FLAGRANT_1_OF_3,
            Plays.MISSES_FREE_THROW_FLAGRANT_2_OF_3,
            Plays.MISSES_FREE_THROW_FLAGRANT_3_OF_3,
            }

technical_ft = {Plays.MAKES_TECHNICAL_FREE_THROW,
                Plays.MISSES_TECHNICAL_FREE_THROW}


